version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - app_logs_data:/app/logs

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_rest_danilov
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_logs_data: